### ISSUE TITLE
Project seems to be broken

### ISSUE THREAD

**Issue by hahnicity** [colinpollock/amazon-scraper#2]
Using url: http://www.amazon.com/Minecraft-Guide-Unbelievable-Handbook-minecraft-ebook/dp/B00SA2Y6QY/

I tried to get a list of reviews as the documentation recommended.

```
url = "http://www.amazon.com/Minecraft-Guide-Unbelievable-Handbook-minecraft-ebook/dp/B00SA2Y6QY/"
>>> rev = scrape.Product(url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "scrape.py", line 198, in __init__
    self.reviews = self.scrape_reviews()
  File "scrape.py", line 208, in scrape_reviews
    urls = self._get_review_urls()
  File "scrape.py", line 238, in _get_review_urls
    url = match.groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
```

I'd venture that since this project hasn't been touched in awhile its broken

**Comment by felipefm** [comment]
"If Amazon were to make small changes to how they render pages then this script would probably break."
https://github.com/colinpollock/amazon-scraper#about[](url)
